apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: conditionfoo
  namespace: testns
spec:
  check:
    image: alpine
    name: "check"
    resources: {}
    script: 'test -f $(resources.workspace.path)/$(params.path)'
  params:
    - name: "path"
      type: string
  resources:
    - name: workspace
      type: git
