apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: resourcefoo
  namespace: testns
spec:
  type: git
  params:
    - name: url
      value: https://github.com/fake/fake.git
    - name: revision
      value: master